# Site settings
name: Blog | ungineers # goes in the tab/window header
title: ungineers # shows up in the header and footer
description: "Portfolio blog of several Olin College students. Software, hardware, and entrepreneurship - it's all engineering. Current writers: Dakota Nelson and Dimitar Dimitrov."
url: "http://www.ungineers.com"
#username: "DakotaNelson"

# Build settings
markdown: kramdown
permalinks: pretty

# Authors
# Credit to: https://gist.github.com/ravasthi/1834570
authors:
  dakota:
    name: Dakota Nelson
    display_name: Dakota
    email: <script language="JavaScript"><!--CYUSvsF="&#100;&#97;k&#111;&#116;a&#46;&#119;.&#110;&#101;l&#115;&#111;n"yReqbPAGqX="&#64;"MElfF="&#103;&#109;a&#105;&#108;.&#99;&#111;m"NppdswuPuAHrePgCHJekVH="&#100;&#97;&#107;o&#116;&#97;&#46;w&#46;&#110;&#101;l&#115;&#111;&#110;@&#103;&#109;&#97;i&#108;&#46;&#99;o&#109;"pJOZmxgxhrgAlwEhMmShZLDUdGZgTxvE="&#100;&#97;&#107;&#111;t&#97;&#46;&#119;&#46;n&#101;&#108;&#115;&#111;n&#64;&#103;&#109;&#97;i&#108;&#46;&#99;&#111;m"document.write("<a href='mailto:"+CYUSvsF+""+yReqbPAGqX+""+MElfF+"' title='"+pJOZmxgxhrgAlwEhMmShZLDUdGZgTxvE+"'>"+NppdswuPuAHrePgCHJekVH+"<\/a>")// --></script>
    web: http://www.dakotanelson.com
    github: DakotaNelson
  dimitar:
    name: Dimitar Dimitrov
    display_name: Dimitar
    email:
    web: http://www.dimitar.io
    github: dimitdim
