# Site settings
name: Blog | Dakota Nelson
title: Some sort of awesome subtitle.
#email: your-email@domain.com
#description: "Site description. We should probably write something cool here. Blah blah lorem ipsum spacing words stuff fill space blergh. Yay for filler text!"
baseurl: "/blog"
url: "http://www.dakotanelson.com/blog"
#username: "DakotaNelson"

# Build settings
markdown: kramdown
permalinks: pretty

# Authors
# Credit to: https://gist.github.com/ravasthi/1834570
authors:
  dakota:
    name: Dakota Nelson
    display_name: Dakota
    email: <script language="JavaScript"><!--CYUSvsF="&#100;&#97;k&#111;&#116;a&#46;&#119;.&#110;&#101;l&#115;&#111;n"yReqbPAGqX="&#64;"MElfF="&#103;&#109;a&#105;&#108;.&#99;&#111;m"NppdswuPuAHrePgCHJekVH="&#100;&#97;&#107;o&#116;&#97;&#46;w&#46;&#110;&#101;l&#115;&#111;&#110;@&#103;&#109;&#97;i&#108;&#46;&#99;o&#109;"pJOZmxgxhrgAlwEhMmShZLDUdGZgTxvE="&#100;&#97;&#107;&#111;t&#97;&#46;&#119;&#46;n&#101;&#108;&#115;&#111;n&#64;&#103;&#109;&#97;i&#108;&#46;&#99;&#111;m"document.write("<a href='mailto:"+CYUSvsF+""+yReqbPAGqX+""+MElfF+"' title='"+pJOZmxgxhrgAlwEhMmShZLDUdGZgTxvE+"'>"+NppdswuPuAHrePgCHJekVH+"<\/a>")// --></script>
    web: http://www.dakotanelson.com
    github: DakotaNelson
