# Site settings
name: Dat site title tho
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty

# Authors
# Credit to: https://gist.github.com/ravasthi/1834570
authors:
  dakota:
    name: Dakota Nelson
    display_name: Dakota
    email: dakota.w.nelson@gmail.com
    web: http://www.dakotanelson.com
    github: DakotaNelson
