# Site settings
name: Dat site title tho
title: Some sort of awesome subtitle.
#email: your-email@domain.com
description: "Site description. We should probably write something cool here."
baseurl: "/blog"
url: "http://www.dakotanelson.com/blog"

# Build settings
markdown: kramdown
permalinks: pretty

# Authors
# Credit to: https://gist.github.com/ravasthi/1834570
authors:
  dakota:
    name: Dakota Nelson
    display_name: Dakota
    email: dakota.w.nelson@gmail.com
    web: http://www.dakotanelson.com
    github: DakotaNelson
